/station_default:
  - action_type: decrement_data_key
    params:
      key: ttl
  
  - action_type: log_parcel

  - action_type: wait
    params:
      seconds: 1

  - action_type: conditional
    params:
      condition:
        run_action: check_ttl
        params:
          key: ttl

      if_true:
        run_action: forward
        params:
          destination: /station_next

      if_false:
        run_action: kill

/station_next:
  - action_type: decrement_data_key
    params:
      key: ttl
  
  - action_type: log_parcel

  - action_type: conditional
    params:
      condition:
        run_action: check_ttl
        params:
          key: ttl

      if_true:
        run_action: forward
        params:
          destination: /station_default

      if_false:
        run_action: kill
