/rospi_1:
  - action_type: decrement_data_key
    params:
      key: ttl

  - action_type: conditional
    params:
      condition:
        run_action: check_ttl
        params:
          key: ttl

      if_true:
        run_action: forward
        params:
          destination: /rospi_2

      if_false:
        run_action: kill
  - action_type: log_parcel

/rospi_2:
  - action_type: decrement_data_key
    params:
      key: ttl
  
  - action_type: log_parcel

  - action_type: conditional
    params:
      condition:
        run_action: check_ttl
        params:
          key: ttl

      if_true:
        run_action: forward
        params:
          destination: /rospi_3

      if_false:
        run_action: kill

/rospi_3:
  - action_type: decrement_data_key
    params:
      key: ttl
  
  - action_type: log_parcel

  - action_type: conditional
    params:
      condition:
        run_action: check_ttl
        params:
          key: ttl

      if_true:
        run_action: forward
        params:
          destination: /rospi_4

      if_false:
        run_action: kill

/rospi_4:
  - action_type: decrement_data_key
    params:
      key: ttl
  
  - action_type: log_parcel

  - action_type: conditional
    params:
      condition:
        run_action: check_ttl
        params:
          key: ttl

      if_true:
        run_action: forward
        params:
          destination: /rospi_1

      if_false:
        run_action: kill
  
